portfolio -47 created banner, functionality, 95%
nikolabojkovic/nikolabojkovic.github.io pull request #93
Opened 2022-06-10 07:05 UTC by MarkoBojkovicGithub

Portfolio 47, banner,fuctionality 95%

2022-06-11 08:30 UTC, nikolabojkovic requested changes

2022-06-11 08:30 UTC, nikolabojkovic commented on portfolio/src/app/home/banner/banner.component.html
> +        <h1 class = "all-text-container__body">Hi, I'm <span style = "color:var(--text-secondary-color)">Nikola Bojkovic</span></h1>
Please use class instead of style. Please move css code to scss file.

2022-06-11 08:30 UTC, nikolabojkovic commented on portfolio/src/app/home/banner/banner.component.scss
> +
Please remove extra empty lines.

2022-06-11 08:30 UTC, nikolabojkovic commented on portfolio/src/app/home/banner/banner.component.scss
> +    }
Please put empty line between class definitions.

2022-06-11 08:30 UTC, nikolabojkovic commented on portfolio/src/app/home/banner/banner.component.ts
> +    if(window.innerWidth < 1500) {
Please place number 1500 in const variable and give it a name "WIDE_SCREEEN_SIZE". For example 
const WIDE_SCREEN_SIZE = 1500 and use it in if statement like this 
if (widnow.innerWidth < WIDE_SCREEEN_SIZE)

2022-06-13 07:21 UTC, MarkoBojkovicGithub commented
finished

2022-06-13 07:23 UTC, nikolabojkovic approved these changes

2022-06-13 07:23 UTC, merged